apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksworkshop-a6bc"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksworkshop-a6bc"
  template:
    metadata:
      labels:
        app: "aksworkshop-a6bc"
    spec:
      containers:
        - name: "aksworkshop-a6bc"
          image: "aksworkshopregistry.azurecr.io/aksworkshop"
          ports:
          - containerPort: 80