apiVersion: v1
kind: Service
metadata:
    name: "aksworkshop-3f99"
    labels:
        app: "aksworkshop-3f99"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksworkshop-3f99"